_:
  - &docker_credentials
    username: aleem
    password:
      from_secret: docker_registry
  - &cached_volumes
    - name: docker
      path: /var/lib/docker
    - name: go
      path: /go-cache
  - &linux_amd64_environment
    GOOS: linux
    GOARCH: amd64

kind: pipeline
name: default

# Build and push a test image before using it in the next step to actually run
#   the tests.
steps:
  - name: prepare
    image: busybox
    commands:
      - echo "${DRONE_RUNNER_HOSTNAME}"
      - if [ "${DRONE_RUNNER_HOSTNAME}" == "util2" ]; then echo "util2 disabled for performance reasons" && exit 1; fi
      - mkdir -p /cache/docker cache/go
    volumes:
      - name: cache
        path: /cache

  - name: create-test-image
    image: plugins/docker
    settings:
      repo: registry.internal.aleemhaji.com/test-container
      tags: latest
      dockerfile: TestDockerfile
      registry: registry.internal.aleemhaji.com
      <<: *docker_credentials
    volumes: *cached_volumes

  - name: test
    image: registry.internal.aleemhaji.com/test-container:latest
    pull: false
    commands:
      - cp -r /go-cache/* /go/
      - make test system-test
      - rm -rf /go-cache/* && cp -r /go/* /go-cache/
    volumes: *cached_volumes
    environment:
      <<: *linux_amd64_environment

  - name: build
    image: registry.internal.aleemhaji.com/test-container:latest
    pull: false
    commands:
      - make install
    volumes: *cached_volumes
    environment:
      <<: *linux_amd64_environment

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
      channel: ci
    when:
      status:
        - failure

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/docker
  - name: go
    host:
      path: /var/cache/go

image_pull_secrets:
  - dockerconfigjson
