kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.12
    commands:
      - make test system-test
  - name: build
    image: golang:1.12
    commands:
      - make install
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
      channel: ci
    when:
      status:
        - failure
